# GitHub Actions workflow to upload a Python package to PyPI on every push to main
name: Upload Python Package

on:
  push:
    branches:
      - main  
permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry pytest build
      
      - name: Run tests
        run: |
          pytest || exit 1  # If tests fail, stop the workflow

      - name: Build package distributions
        run: |
          python -m build

      - name: Upload built distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: test-build  # Runs only after successful testing

    permissions:
      id-token: write  # Required for Trusted Publishing

    environment:
      name: pypi
      url: https://pypi.org/project/msfootprint/

    steps:
      - name: Retrieve built distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
